export type Finish = {
  id: string;
  name: string;
  caption: string;
  swatch: string;
  metal: string;
  metalness: number;
  roughness: number;
  clearcoat: number;
  clearcoatRoughness: number;
  envMapIntensity: number;
  emissive: string;
  emissiveIntensity: number;
  cushion: string;
  inner: string;
  hardware: string;
};

export const FINISHES: Finish[] = [
  {
    id: "graphite",
    name: "Grafito",
    caption: "Aluminio anodizado mate",
    swatch: "#3a3d42",
    metal: "#4a4f57",
    metalness: 0.72,
    roughness: 0.38,
    clearcoat: 0.35,
    clearcoatRoughness: 0.4,
    envMapIntensity: 1,
    emissive: "#000000",
    emissiveIntensity: 0,
    cushion: "#1a1c1f",
    inner: "#111214",
    hardware: "#8b9098",
  },
  {
    id: "polar",
    name: "Polar",
    caption: "Aluminio cepillado",
    swatch: "#d5d8de",
    metal: "#c5cad2",
    metalness: 0.95,
    roughness: 0.22,
    clearcoat: 0.7,
    clearcoatRoughness: 0.25,
    envMapIntensity: 1.15,
    emissive: "#000000",
    emissiveIntensity: 0,
    cushion: "#ece7e0",
    inner: "#b8bcc4",
    hardware: "#9aa1ab",
  },
  {
    id: "ivory",
    name: "Marfil",
    caption: "Cerámica suave",
    swatch: "#e8e0d2",
    metal: "#e4d9c8",
    metalness: 0.45,
    roughness: 0.42,
    clearcoat: 0.55,
    clearcoatRoughness: 0.35,
    envMapIntensity: 0.85,
    emissive: "#000000",
    emissiveIntensity: 0,
    cushion: "#cbbba6",
    inner: "#a89884",
    hardware: "#b7a790",
  },
  {
    id: "slate",
    name: "Pizarra",
    caption: "Laca azul-gris",
    swatch: "#4d5968",
    metal: "#3e4a58",
    metalness: 0.55,
    roughness: 0.38,
    clearcoat: 0.8,
    clearcoatRoughness: 0.22,
    envMapIntensity: 1.05,
    emissive: "#000000",
    emissiveIntensity: 0,
    cushion: "#1e242c",
    inner: "#14181e",
    hardware: "#8a97a6",
  },
  {
    id: "ink",
    name: "Tinta",
    caption: "DLC profundo",
    swatch: "#1b1e24",
    metal: "#16181c",
    metalness: 0.7,
    roughness: 0.28,
    clearcoat: 0.9,
    clearcoatRoughness: 0.18,
    envMapIntensity: 1.1,
    emissive: "#000000",
    emissiveIntensity: 0,
    cushion: "#0e1013",
    inner: "#090a0c",
    hardware: "#6e747c",
  },
  {
    id: "chrome",
    name: "Metal",
    caption: "Cromo pulido, refleja el estudio",
    swatch: "#c5ced8",
    metal: "#e4ebf2",
    metalness: 1,
    roughness: 0.08,
    clearcoat: 0.35,
    clearcoatRoughness: 0.08,
    envMapIntensity: 1.85,
    emissive: "#000000",
    emissiveIntensity: 0,
    cushion: "#9aa3ad",
    inner: "#6d7680",
    hardware: "#f2f5f8",
  },
  {
    id: "mirror",
    name: "Espejo",
    caption: "Reflexión casi perfecta",
    swatch: "#f4f7fb",
    metal: "#f7fbff",
    metalness: 1,
    roughness: 0,
    clearcoat: 1,
    clearcoatRoughness: 0,
    envMapIntensity: 2.6,
    emissive: "#000000",
    emissiveIntensity: 0,
    cushion: "#d5dde6",
    inner: "#aeb8c4",
    hardware: "#ffffff",
  },
  {
    id: "coldlight",
    name: "Luz fría",
    caption: "Emisión verde fría, brillante",
    swatch: "#5dffc6",
    metal: "#10241e",
    metalness: 0.2,
    roughness: 0.32,
    clearcoat: 0.45,
    clearcoatRoughness: 0.2,
    envMapIntensity: 0.35,
    emissive: "#8affe0",
    emissiveIntensity: 2.4,
    cushion: "#0c1a16",
    inner: "#07110e",
    hardware: "#b8fff0",
  },
  {
    id: "gold",
    name: "Oro",
    caption: "Oro pulido",
    swatch: "#e2c072",
    metal: "#d4b067",
    metalness: 1,
    roughness: 0.16,
    clearcoat: 0.45,
    clearcoatRoughness: 0.12,
    envMapIntensity: 1.7,
    emissive: "#000000",
    emissiveIntensity: 0,
    cushion: "#8a6a32",
    inner: "#5c451c",
    hardware: "#f3e2b0",
  },
  {
    id: "copper",
    name: "Cobre",
    caption: "Cobre cálido",
    swatch: "#c4784a",
    metal: "#b8734a",
    metalness: 1,
    roughness: 0.22,
    clearcoat: 0.3,
    clearcoatRoughness: 0.16,
    envMapIntensity: 1.45,
    emissive: "#000000",
    emissiveIntensity: 0,
    cushion: "#6e3d28",
    inner: "#4a2818",
    hardware: "#e8b08a",
  },
  {
    id: "ruby",
    name: "Rubí",
    caption: "Laca roja profunda",
    swatch: "#8e1d32",
    metal: "#7a1528",
    metalness: 0.35,
    roughness: 0.22,
    clearcoat: 1,
    clearcoatRoughness: 0.06,
    envMapIntensity: 1.2,
    emissive: "#000000",
    emissiveIntensity: 0,
    cushion: "#3a0c14",
    inner: "#24080e",
    hardware: "#e8b4be",
  },
  {
    id: "emerald",
    name: "Esmeralda",
    caption: "Verde joya",
    swatch: "#0f6b45",
    metal: "#0d5c3c",
    metalness: 0.4,
    roughness: 0.24,
    clearcoat: 0.9,
    clearcoatRoughness: 0.08,
    envMapIntensity: 1.15,
    emissive: "#000000",
    emissiveIntensity: 0,
    cushion: "#0a2e1e",
    inner: "#061910",
    hardware: "#b7e2cf",
  },
  {
    id: "sapphire",
    name: "Zafiro",
    caption: "Azul profundo",
    swatch: "#1d3f8f",
    metal: "#17357a",
    metalness: 0.42,
    roughness: 0.2,
    clearcoat: 0.95,
    clearcoatRoughness: 0.08,
    envMapIntensity: 1.25,
    emissive: "#000000",
    emissiveIntensity: 0,
    cushion: "#0c1838",
    inner: "#070e22",
    hardware: "#c5d4f5",
  },
  {
    id: "violet",
    name: "Violeta",
    caption: "Laca violeta",
    swatch: "#5b2d82",
    metal: "#4e2670",
    metalness: 0.38,
    roughness: 0.24,
    clearcoat: 0.85,
    clearcoatRoughness: 0.1,
    envMapIntensity: 1.1,
    emissive: "#000000",
    emissiveIntensity: 0,
    cushion: "#241033",
    inner: "#14081e",
    hardware: "#ddc6f0",
  },
  {
    id: "pearl",
    name: "Perla",
    caption: "Nácar suave",
    swatch: "#f3ece4",
    metal: "#f6f0e8",
    metalness: 0.15,
    roughness: 0.28,
    clearcoat: 0.7,
    clearcoatRoughness: 0.18,
    envMapIntensity: 0.9,
    emissive: "#000000",
    emissiveIntensity: 0,
    cushion: "#e4d5c8",
    inner: "#cbb8a8",
    hardware: "#fffaf5",
  },
  {
    id: "neon",
    name: "Neón",
    caption: "Magenta que emite luz",
    swatch: "#ff3dbe",
    metal: "#2a0c22",
    metalness: 0.15,
    roughness: 0.3,
    clearcoat: 0.4,
    clearcoatRoughness: 0.2,
    envMapIntensity: 0.35,
    emissive: "#ff4ad2",
    emissiveIntensity: 2.2,
    cushion: "#1a0816",
    inner: "#10040d",
    hardware: "#ffd0f0",
  },
];

export const ORIGINAL_FINISH: Finish = {
  id: "original",
  name: "Normal",
  caption: "El material del modelo, sin tinte",
  swatch: "#d4d4d8",
  metal: "#c5cad2",
  metalness: 0.7,
  roughness: 0.35,
  clearcoat: 0.2,
  clearcoatRoughness: 0.3,
  envMapIntensity: 1,
  emissive: "#000000",
  emissiveIntensity: 0,
  cushion: "#ece7e0",
  inner: "#b8bcc4",
  hardware: "#9aa1ab",
};

export function getFinish(id: string): Finish {
  if (id === ORIGINAL_FINISH.id) return ORIGINAL_FINISH;
  return FINISHES.find((item) => item.id === id) ?? FINISHES[0]!;
}
